import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

export interface SendOtpResult {
  success: boolean;
  sessionId?: string;
  message?: string;
  isMocked?: boolean;
}

export interface VerifyOtpResult {
  success: boolean;
  message?: string;
}

@Injectable()
export class TwoFactorService {
  private readonly logger = new Logger(TwoFactorService.name);
  private readonly apiKey: string | undefined;
  private readonly templateName: string | undefined;
  private readonly baseUrl = 'https://2factor.in/API/V1';

  constructor(private readonly configService: ConfigService) {
    this.apiKey = this.configService.get<string>('TWOFACTOR_API_KEY')?.trim();
    this.templateName = this.configService.get<string>('TWOFACTOR_OTP_TEMPLATE')?.trim();

    if (!this.apiKey) {
      this.logger.warn(
        '⚠️ TWOFACTOR_API_KEY is not configured in .env. Real SMS will not be dispatched; OTPs will be logged to console in mock mode.',
      );
    } else {
      this.logger.log('✅ TwoFactorService initialized with API key.');
    }
  }

  /**
   * Normalize phone number for 2Factor API.
   * 2Factor India API accepts digits without "+" prefix.
   * E.g.: "+919876543210" -> "919876543210"
   * E.g.: "9876543210" -> "919876543210" (defaults to India 91 if 10 digits)
   */
  public normalizePhone(rawPhone: string): string {
    let clean = rawPhone.replace(/[^0-9]/g, '');
    if (clean.length === 10) {
      clean = `91${clean}`;
    }
    return clean;
  }

  /**
   * Send custom OTP via 2Factor.in SMS API.
   * Format: https://2factor.in/API/V1/{apiKey}/SMS/{phone}/{otp}/{template_name}
   */
  async sendOtp(phone: string, otp: string): Promise<SendOtpResult> {
    const formattedPhone = this.normalizePhone(phone);

    if (!this.apiKey) {
      this.logger.warn(
        `[MOCK 2FACTOR] Sending OTP ${otp} to phone ${formattedPhone} (No TWOFACTOR_API_KEY configured)`,
      );
      return {
        success: true,
        message: 'Mock OTP generated (API key not configured)',
        isMocked: true,
      };
    }

    try {
      // If template is specified: /SMS/{phone}/{otp}/{template_name}, else /SMS/{phone}/{otp}
      const endpoint = this.templateName
        ? `${this.baseUrl}/${encodeURIComponent(this.apiKey)}/SMS/${formattedPhone}/${encodeURIComponent(otp)}/${encodeURIComponent(this.templateName)}`
        : `${this.baseUrl}/${encodeURIComponent(this.apiKey)}/SMS/${formattedPhone}/${encodeURIComponent(otp)}`;

      this.logger.log(`Calling 2Factor API to send OTP to ${formattedPhone}...`);

      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000);

      const response = await fetch(endpoint, {
        method: 'GET',
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      const data: any = await response.json();

      if (data && (data.Status === 'Success' || data.status === 'Success')) {
        this.logger.log(`✅ 2Factor OTP dispatched successfully to ${formattedPhone}. Session: ${data.Details}`);
        return {
          success: true,
          sessionId: data.Details,
          message: 'OTP SMS sent successfully',
        };
      } else {
        const errorDetail = data?.Details || data?.message || JSON.stringify(data);
        this.logger.error(`❌ 2Factor API error sending OTP to ${formattedPhone}: ${errorDetail}`);
        return {
          success: false,
          message: errorDetail,
        };
      }
    } catch (error: any) {
      this.logger.error(
        `❌ Failed to call 2Factor API for ${formattedPhone}: ${error?.message || error}`,
      );
      return {
        success: false,
        message: error?.message || 'Failed to dispatch SMS via 2Factor',
      };
    }
  }

  /**
   * Verify an autogenerated OTP via 2Factor session if autogen was used.
   * Format: https://2factor.in/API/V1/{apiKey}/SMS/VERIFY/{sessionId}/{otp}
   */
  async verifySessionOtp(sessionId: string, otp: string): Promise<VerifyOtpResult> {
    if (!this.apiKey) {
      return { success: true, message: 'Mock verification' };
    }

    try {
      const endpoint = `${this.baseUrl}/${encodeURIComponent(this.apiKey)}/SMS/VERIFY/${encodeURIComponent(sessionId)}/${encodeURIComponent(otp)}`;
      const response = await fetch(endpoint, { method: 'GET' });
      const data: any = await response.json();

      if (data && (data.Status === 'Success' || data.Details === 'OTP Matched')) {
        return { success: true, message: 'OTP verified successfully' };
      }

      return {
        success: false,
        message: data?.Details || 'Invalid OTP',
      };
    } catch (error: any) {
      this.logger.error(`Error verifying 2Factor session OTP: ${error?.message || error}`);
      return { success: false, message: error?.message || 'Verification failed' };
    }
  }
}
